name: Веха
title: Веха
titles:
  en: Milestone
  de: Meilenstein
  sr: Мељок
  az: Mərhələ
  es: Hito
  fr: Jalon
  hy: Ուղենիշ
  ka: ეტაპი
  kk: Кезең
  pt: Marco
  ro: Piatră de hotar
  tr: Kilometre taşı
  uk: Віха
  uz: Bosqich
  zh: 里程碑
fields:
  - name: Наименование
    type: string
    title: Наименование
    titles:
      en: Name
      de: Name
      sr: Назив
      az: Adlandırma
      es: Nombre
      fr: Nom
      hy: Անվանում
      ka: დასახელება
      kk: Атауы
      pt: Nome
      ro: Denumire
      tr: Ad
      uk: Найменування
      uz: Nomi
      zh: 名称
  - name: Проект
    type: reference:Проект
    title: Проект
    titles:
      en: Project
      de: Projekt
      sr: Пројекат
      az: Layihə
      es: Proyecto
      fr: Projet
      hy: Նախագիծ
      ka: პროექტი
      kk: Жоба
      pt: Projeto
      ro: Proiect
      tr: Proje
      uk: Проєкт
      uz: Loyiha
      zh: 项目
  - name: ДатаНачала
    type: date
    title: Дата начала
    titles:
      en: Start date
      de: Startdatum
      sr: Датум почетка
      az: Başlama tarixi
      es: Fecha de inicio
      fr: Date de début
      hy: Սկզբի ամսաթիվ
      ka: დაწყების თარიღი
      kk: Басталу күні
      pt: Data de início
      ro: Dată de început
      tr: Başlangıç tarihi
      uk: Дата початку
      uz: Boshlanish sanasi
      zh: 开始日期
  - name: ДатаЗавершения
    type: date
    title: Дедлайн
    titles:
      en: Deadline
      de: Frist
      sr: Рок
      az: Son tarix
      es: Fecha límite
      fr: Date limite
      hy: Վերջնաժամկետ
      ka: ბოლო ვადა
      kk: Мерзімі
      pt: Prazo
      ro: Termen limită
      tr: Son tarih
      uk: Дедлайн
      uz: Muddat
      zh: 截止日期
  - name: Описание
    type: string
    title: Описание
    titles:
      en: Description
      de: Beschreibung
      sr: Опис
      az: Təsvir
      es: Descripción
      fr: Description
      hy: Նկարագրություն
      ka: აღწერა
      kk: Сипаттамасы
      pt: Descrição
      ro: Descriere
      tr: Açıklama
      uk: Опис
      uz: Tavsif
      zh: 描述
